import { CONTROLS } from "./controls/index.ts";
import type { Report, Severity } from "./types.ts";

export const BLOCK_BEGIN = "<!-- codex-loop:begin -->";
export const BLOCK_END = "<!-- codex-loop:end -->";
export const DEFAULT_MAX_CHARS = 3500;

const RANK: Record<Severity, number> = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };

export interface AgentsMdOptions {
  /** Character budget for the managed block; lowest-severity rules are dropped first. */
  maxChars?: number;
}

/**
 * The managed block only. Deterministic for a given report (no timestamps) so regenerating it
 * in CI produces no diff unless the repo or the standards actually changed.
 */
export function renderManagedBlock(report: Report, opts: AgentsMdOptions = {}): string {
  const budget = Math.max(800, opts.maxChars ?? DEFAULT_MAX_CHARS);
  const p = report.profile;
  const lines: string[] = [BLOCK_BEGIN, "## Repository guide for coding agents", ""];
  lines.push("_Generated by codex-loop from this repository's engineering standards. Edit outside this block; regenerate with `codex-loop context --write`._", "");

  lines.push("### Project");
  if (p.languages.length) lines.push(`- Languages: ${p.languages.join(", ")}`);
  const pm = p.packageManager ? `${p.packageManager}${p.monorepo ? ", monorepo" : ""}` : p.monorepo ? "monorepo" : "";
  if (pm) lines.push(`- Tooling: ${pm}`);
  // Only stable facts belong here: an exact file count would make the drift gate fail on every new file.
  lines.push(`- Scale: ${p.sizeBucket} repository`, "");

  const cmds = Object.entries(p.commands) as Array<[string, string]>;
  if (cmds.length) {
    lines.push("### Commands", "_Discovered from manifests; verify before relying on them._");
    const order = ["install", "build", "test", "lint", "typecheck", "dev"];
    for (const key of order) {
      const cmd = p.commands[key as keyof typeof p.commands];
      if (cmd) lines.push(`- ${key[0]!.toUpperCase()}${key.slice(1)}: \`${cmd}\``);
    }
    lines.push("");
  }

  const byId = new Map(CONTROLS.map((c) => [c.id, c]));
  const applicable = report.results
    .filter((r) => r.status !== "na")
    .map((r) => ({ r, c: byId.get(r.id) }))
    .filter((x): x is { r: (typeof report.results)[number]; c: NonNullable<typeof x.c> } => x.c !== undefined)
    .sort((a, b) => RANK[a.r.severity] - RANK[b.r.severity] || a.r.id.localeCompare(b.r.id));

  lines.push("### Standards", "Ordered by severity. **(violated today)** means this repo currently fails the standard: do not add new violations, and fix existing ones when you touch the related files.");
  const footer = (omitted: number) => [
    ...(omitted > 0 ? [`- _${omitted} lower-severity rule(s) omitted to stay within the context budget._`] : []),
    "",
    "### Before you finish",
    "- Run the build, test and lint commands above and fix what you break.",
    "- Keep changes small and scoped; mention any standard you could not satisfy and why.",
    BLOCK_END
  ];

  const rules: string[] = [];
  for (const { r, c } of applicable) {
    // CDX-070 is about this very file existing, so marking it would make the block depend on itself and
    // break the fixed point (`--write` followed by `--check` must always pass).
    const violated = r.status === "fail" && !r.exception && r.id !== "CDX-070" ? " **(violated today)**" : "";
    rules.push(`- **${r.id}** ${c.agentRule}${violated}`);
  }
  let used = lines.join("\n").length + footer(0).join("\n").length + 60;
  let kept = 0;
  for (const rule of rules) {
    if (used + rule.length + 1 > budget) break;
    lines.push(rule);
    used += rule.length + 1;
    kept++;
  }
  lines.push(...footer(rules.length - kept));
  return lines.join("\n");
}

/** A standalone AGENTS.md file: title plus the managed block. */
export function renderAgentsMd(report: Report, opts: AgentsMdOptions = {}): string {
  return `# AGENTS.md\n\n${renderManagedBlock(report, opts)}\n`;
}

/** Insert or replace the managed block inside existing content without touching anything else. */
export function upsertManagedBlock(existing: string | null, block: string): string {
  if (existing === null || existing.trim() === "") return `# AGENTS.md\n\n${block}\n`;
  const start = existing.indexOf(BLOCK_BEGIN);
  const end = existing.indexOf(BLOCK_END);
  if (start !== -1 && end !== -1 && end > start) {
    return existing.slice(0, start) + block + existing.slice(end + BLOCK_END.length);
  }
  return `${existing.replace(/\s*$/, "")}\n\n${block}\n`;
}
