/**
 * Input validation for every HTTP entry point. Pure (no Workers APIs beyond web-standard
 * streams), so it is unit-tested in plain Node. Anything that reaches GitHub, a Durable
 * Object name or a model prompt passes through here first.
 */
import { ApiError } from "./errors.ts";

export const MAX_BODY_BYTES = 8 * 1024;
export const MAX_REPO_INPUT_CHARS = 300;
export const MAX_CHAT_MESSAGE_CHARS = 2000;

/** GitHub owner / repository name alphabet (slightly wider than owners, which forbid "_" and "."). */
export const NAME_RE = /^[A-Za-z0-9_.-]{1,100}$/;
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const CONTROL_ID_RE = /^[A-Za-z0-9_.-]{1,40}$/;
const REF_RE = /^[A-Za-z0-9][A-Za-z0-9._/-]{0,199}$/;

export interface RepoCoordinates {
  owner: string;
  repo: string;
}

export function isValidName(name: string): boolean {
  return NAME_RE.test(name) && !/^\.+$/.test(name);
}

/** Canonical Durable Object name / cache key: lowercase "owner/repo". */
export function repoKey(owner: string, repo: string): string {
  return `${owner}/${repo}`.toLowerCase();
}

/** Validates (already URL-decoded) path segments. */
export function parseRepoParams(owner: string | undefined, repo: string | undefined): RepoCoordinates {
  if (!owner || !repo || !isValidName(owner) || !isValidName(repo)) {
    throw new ApiError(400, "bad_input", "Use the form owner/name with letters, digits, '.', '_' or '-'.");
  }
  return { owner, repo };
}

/** Returns "" for "default branch". Rejects anything that is not a plain git ref or SHA. */
export function validateRef(ref: unknown): string {
  if (ref === undefined || ref === null || ref === "") return "";
  if (typeof ref !== "string") throw new ApiError(400, "bad_input", "ref must be a string.");
  const r = ref.trim();
  if (r === "") return "";
  if (
    !REF_RE.test(r) ||
    r.includes("..") ||
    r.includes("//") ||
    r.endsWith("/") ||
    r.endsWith(".") ||
    r.endsWith(".lock") ||
    r.includes("/.")
  ) {
    throw new ApiError(400, "bad_input", "ref is not a valid branch, tag or commit.");
  }
  return r;
}

export type RepoParser = (input: string) => RepoCoordinates | null;

export type AnalyzeRequest = RepoCoordinates;

export const REF_UNSUPPORTED_MESSAGE =
  "Analyzing a specific ref is not supported by the hosted service, which always analyzes the default branch. Use the CLI instead: codex-loop remote owner/repo --ref <ref>.";

/**
 * The parser is injected (core's parseRepoInput in production) and then re-checked strictly here.
 * `ref` is deliberately rejected: a caller-chosen ref would overwrite the shared per-repo report.
 */
export function validateAnalyzeRequest(body: unknown, parse: RepoParser): AnalyzeRequest {
  const obj = asObject(body);
  if (obj.ref !== undefined && obj.ref !== null) {
    throw new ApiError(400, "bad_input", REF_UNSUPPORTED_MESSAGE);
  }
  const input = obj.repo;
  if (typeof input !== "string" || input.trim() === "") {
    throw new ApiError(400, "bad_request", "Body must be JSON like {\"repo\": \"owner/name\"}.");
  }
  if (input.length > MAX_REPO_INPUT_CHARS) {
    throw new ApiError(400, "bad_input", "Repository input is too long.");
  }
  let parsed: RepoCoordinates | null;
  try {
    parsed = parse(input.trim());
  } catch {
    parsed = null;
  }
  if (!parsed) {
    throw new ApiError(400, "bad_input", "Enter a public GitHub repository as owner/name or a github.com URL.");
  }
  return parseRepoParams(parsed.owner, parsed.repo);
}

/** Chat history is scoped to a browser session: a random UUID sent as `X-Session-Id`. */
export function validateSessionId(header: string | null): string {
  const v = header?.trim().toLowerCase() ?? "";
  if (!UUID_RE.test(v)) {
    throw new ApiError(400, "bad_request", "X-Session-Id header (a random UUID generated by the client) is required.");
  }
  return v;
}

export function validateChatRequest(body: unknown): { message: string } {
  const obj = asObject(body);
  const message = obj.message;
  if (typeof message !== "string") {
    throw new ApiError(400, "bad_request", "Body must be JSON like {\"message\": \"...\"}.");
  }
  // eslint-disable-next-line no-control-regex
  const cleaned = message.replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/g, "").trim();
  if (cleaned === "") throw new ApiError(400, "bad_request", "message must not be empty.");
  if (cleaned.length > MAX_CHAT_MESSAGE_CHARS) {
    throw new ApiError(400, "bad_request", `message must be at most ${MAX_CHAT_MESSAGE_CHARS} characters.`);
  }
  return { message: cleaned };
}

export function validateControlId(id: string): string {
  if (!CONTROL_ID_RE.test(id)) throw new ApiError(400, "bad_input", "Invalid control id.");
  return id;
}

export function isValidAnalysisId(id: string): boolean {
  return UUID_RE.test(id);
}

function asObject(body: unknown): Record<string, unknown> {
  if (typeof body !== "object" || body === null || Array.isArray(body)) {
    throw new ApiError(400, "bad_request", "Body must be a JSON object.");
  }
  return body as Record<string, unknown>;
}

export function parseJsonObject(text: string): Record<string, unknown> {
  let value: unknown;
  try {
    value = JSON.parse(text);
  } catch {
    throw new ApiError(400, "bad_request", "Body is not valid JSON.");
  }
  return asObject(value);
}

export function requireJsonContentType(contentType: string | null): void {
  if (!contentType || !/^application\/json(?:\s*;|$)/i.test(contentType.trim())) {
    throw new ApiError(415, "unsupported_media_type", "Content-Type must be application/json.");
  }
}

/**
 * Reads at most `maxBytes` of UTF-8 text. Honors Content-Length up front and still counts
 * streamed bytes, so a lying or absent header cannot force a large buffer.
 */
export async function readLimitedText(
  body: ReadableStream<Uint8Array> | null,
  contentLength: string | null,
  maxBytes: number = MAX_BODY_BYTES
): Promise<string> {
  const tooLarge = () => new ApiError(413, "payload_too_large", `Request body must be at most ${maxBytes} bytes.`);
  if (contentLength !== null) {
    const declared = Number(contentLength);
    if (Number.isFinite(declared) && declared > maxBytes) throw tooLarge();
  }
  if (!body) return "";
  const reader = body.getReader();
  const chunks: Uint8Array[] = [];
  let total = 0;
  try {
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      total += value.byteLength;
      if (total > maxBytes) {
        await reader.cancel().catch(() => undefined);
        throw tooLarge();
      }
      chunks.push(value);
    }
  } finally {
    reader.releaseLock();
  }
  const merged = new Uint8Array(total);
  let offset = 0;
  for (const c of chunks) {
    merged.set(c, offset);
    offset += c.byteLength;
  }
  return new TextDecoder().decode(merged);
}

/**
 * CSRF / abuse guard for state-changing requests. Browsers always send Origin on cross-origin
 * POSTs; non-browser clients (curl, MCP hosts) send none and are allowed.
 */
export function checkSameOrigin(headers: Headers, requestUrl: string): void {
  const origin = headers.get("origin");
  if (origin !== null) {
    let same = false;
    try {
      same = new URL(origin).origin === new URL(requestUrl).origin;
    } catch {
      same = false;
    }
    if (!same) throw new ApiError(403, "cross_origin", "Cross-origin requests are not allowed.");
    return;
  }
  if (headers.get("sec-fetch-site") === "cross-site") {
    throw new ApiError(403, "cross_origin", "Cross-origin requests are not allowed.");
  }
}
