/**
 * Compatibility run: analyze a varied set of real public repositories through the same code path
 * the Worker uses, and record what happened. Usage:
 *   npx tsx scripts/compat.ts [--write docs/COMPAT.md] [owner/repo ...]
 * Set GITHUB_TOKEN to raise the API rate limit; without it the run stays small on purpose.
 */
import { writeFile } from "node:fs/promises";
import { analyzeGitHubRepo, GitHubError, parseRepoInput, type Report } from "@codex-loop/core";

const DEFAULT_REPOS = [
  "cloudflare/agents-starter", // TypeScript + wrangler + pnpm/npm
  "expressjs/express", // JavaScript library
  "gin-gonic/gin", // Go
  "pallets/flask", // Python
  "BurntSushi/ripgrep", // Rust
  "docker-library/hello-world", // tiny, Dockerfile-centric
  "octocat/Hello-World", // almost empty
  "vercel/next.js", // very large monorepo (tree may be truncated)
  "cloudflare/this-repository-does-not-exist-404" // error path
];

interface Row {
  repo: string;
  ms: number;
  apiCalls: number;
  rawCalls: number;
  outcome: string;
  report?: Report;
}

const args = process.argv.slice(2);
const writeIdx = args.indexOf("--write");
const outFile = writeIdx !== -1 ? args[writeIdx + 1] : undefined;
const repos = args.filter((a, i) => !a.startsWith("--") && i !== writeIdx + 1 && writeIdx !== i);
const targets = repos.length ? repos : DEFAULT_REPOS;

const rows: Row[] = [];
for (const target of targets) {
  const parsed = parseRepoInput(target);
  if (!parsed) {
    rows.push({ repo: target, ms: 0, apiCalls: 0, rawCalls: 0, outcome: "invalid input" });
    continue;
  }
  let apiCalls = 0;
  let rawCalls = 0;
  const countingFetch: typeof fetch = (input, init) => {
    const url = typeof input === "string" ? input : input instanceof URL ? input.href : input.url;
    if (url.startsWith("https://api.github.com")) apiCalls++;
    else rawCalls++;
    return fetch(input, init);
  };
  const t0 = Date.now();
  try {
    const report = await analyzeGitHubRepo({ ...parsed, includeFootprint: false }, { token: process.env.GITHUB_TOKEN, fetch: countingFetch });
    rows.push({ repo: target, ms: Date.now() - t0, apiCalls, rawCalls, outcome: "ok", report });
  } catch (err) {
    const outcome = err instanceof GitHubError ? `${err.kind}${err.retryAfterSeconds ? ` (retry ${err.retryAfterSeconds}s)` : ""}` : `CRASH: ${err instanceof Error ? err.message : String(err)}`;
    rows.push({ repo: target, ms: Date.now() - t0, apiCalls, rawCalls, outcome });
  }
}

const lines: string[] = [
  "| Repository | Result | Files | Languages | Pass | Fail | Unknown | N/A | Tree truncated | API calls | Raw reads | Time |",
  "|---|---|---:|---|---:|---:|---:|---:|---|---:|---:|---:|"
];
for (const r of rows) {
  const rep = r.report;
  lines.push(
    rep
      ? `| ${r.repo} | ok | ${rep.coverage.filesTotal} | ${rep.profile.languages.slice(0, 3).join(", ") || "-"} | ${rep.summary.pass} | ${rep.summary.fail} | ${rep.summary.unknown} | ${rep.summary.na} | ${rep.coverage.treeTruncated ? "yes" : "no"} | ${r.apiCalls} | ${r.rawCalls} | ${(r.ms / 1000).toFixed(1)}s |`
      : `| ${r.repo} | ${r.outcome} | - | - | - | - | - | - | - | ${r.apiCalls} | ${r.rawCalls} | ${(r.ms / 1000).toFixed(1)}s |`
  );
}
const table = lines.join("\n");
console.log(table);

const crashes = rows.filter((r) => r.outcome.startsWith("CRASH"));
const rateLimited = rows.filter((r) => r.outcome.startsWith("rate_limited"));
console.log(`\n${rows.filter((r) => r.outcome === "ok").length} ok, ${rows.length - rows.filter((r) => r.outcome === "ok").length} non-ok (${crashes.length} crashes, ${rateLimited.length} rate-limited)`);

if (outFile) {
  const note = rateLimited.length ? "\n> Some rows were rate limited by GitHub's unauthenticated limit; re-run with `GITHUB_TOKEN` set for a complete table.\n" : "";
  await writeFile(
    outFile,
    `# Compatibility run\n\nGenerated by \`npm run compat -- --write docs/COMPAT.md\` on ${new Date().toISOString().slice(0, 10)} against the repositories' default branches, using the same code path as the hosted service (GitHub API + raw content, file-read budget of ${40}).\n\n${table}\n${note}\nA non-\`ok\` result for a nonexistent repository is the expected, typed error path. Any \`CRASH\` row would be a bug.\n`,
    "utf8"
  );
  console.log(`wrote ${outFile}`);
}
process.exitCode = crashes.length ? 1 : 0;
