import { CONTROLS } from "../packages/core/src/index.ts";

export function renderControlsDoc(): string {
  const lines: string[] = [
    "# Standards catalog",
    "",
    "<!-- Generated by `npm run docs` from packages/core/src/controls. Do not edit by hand. -->",
    "",
    `${CONTROLS.length} deterministic controls. Each one is a pure function of the repository contents: no network calls, no model output.`,
    "A control returns **pass**, **fail**, **n/a** (does not apply to this repo) or **unknown** (could not be decided; never counted as a failure).",
    "",
    "Default mode is where a control starts in the audit → warn → enforce rollout; a repo can override it per control in `.codex-loop.yml`.",
    "",
    "| ID | Control | Category | Severity | Default mode |",
    "|---|---|---|---|---|",
    ...CONTROLS.map((c) => `| ${c.id} | ${c.title} | ${c.category} | ${c.severity} | ${c.defaultMode ?? "warn"} |`),
    ""
  ];
  for (const c of CONTROLS) {
    lines.push(`## ${c.id}: ${c.title}`, "", `**Why.** ${c.rationale}`, "", `**Fix.** ${c.remediation}`, "", `**Rule given to coding agents.** ${c.agentRule}`, "");
  }
  return lines.join("\n");
}
